on: [push, release, pull_request]
name: testing
jobs:
  test:
    strategy:
      matrix:
        go: [1.14.x, 1.15.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: false
        python-version: 3.5
        activate-environment: ta

    - name: Install Python Deps
      shell: bash -l {0}
      run: |
        conda update -n base -c defaults conda
        conda install -c quantopian ta-lib

    - name: Install Go Deps
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Run Tests
      shell: bash -l {0}
      run: go test -covermode=atomic -coverprofile=profile.cov ./...

    - name: Coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        flag-name: Go-${{ matrix.go }}
        parallel: true
  finish:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - uses: shogo82148/actions-goveralls@v1
          with:
            parallel-finished: true
        - name: Poke proxy.golang.org
          shell: bash -l {0}
          run: |
            cd $(mktemp -d)
            go mod init tmp
            env GOPROXY=https://proxy.golang.org GO111MODULE=on go get go.oneofone.dev/ta@master
